### ISSUE TITLE
Empty tar file uploaded

### ISSUE THREAD

**Issue by nemobis** [rohit-dua/BUB#32]
I see new books coming in, great!

https://catalogd.archive.org/log/397899878 :
```
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

Module threw exception:
tar -xf '/t/derive/bub_gb_pTAPAAAAQAAJ_2/bub_gb_pTAPAAAAQAAJ_images.tar' --directory '/t/_bub_gb_pTAPAAAAQAAJ_2/RawImagesBookPreprocessor-bub_gb_pTAPAAAAQAAJ_2/' failed with exit code: 2
```

https://archive.org/download/bub_gb_pTAPAAAAQAAJ_2 says it's a 0 byte file, so it seems a wrong upload. An error in the tar production, in the upload or in the receiving end?

**Comment by rohit-dua** [comment]
Not sure of the why this happened at that time. But a lot of fixes were made after that.
This probably should not happen again.
Closing the issue.

**Comment by nemobis** [comment]
I'm keeping an eye on the new uploads, sometimes I see a tar file under 100 MB (e.g. https://archive.org/details/bub_gb_3XR76Hj4VB4C ) which might be suspicious, but all looks fine indeed!
