### ISSUE TITLE
Don't download files in home directory

### ISSUE THREAD

**Issue by nemobis** [rohit-dua/BUB#34]
Currently, images are downloaded all together in ~/public_html/BUB/bot/downloads and this is probably not optimal.
1) Tools sysadmins suggest to use /data/scratch for bigger I/O operations. I'm not sure what's the performance difference, but if we overload the /home filesystem there might be some angry daemon beating us.
2) Each book should be downloaded in its own directory. I suspect it's quite easy they might be interfering with each other, occasionally.

**Comment by rohit-dua** [comment]
I've changed the download folder from ~/public_html/BUB/bot/downloads to /data/scratch/BUB_downloads/.
They should not interfere with each other even with the same folder as each file is named with its unique identifier \<library_id>_\<book_id>. 
eg: gb_rMcGAAAAcAAJ_000155.png
