### ISSUE TITLE
Improve Gallica public domain detection

### ISSUE THREAD

**Issue by nemobis** [rohit-dua/BUB#39]
Vigneron reports that http://gallica.bnf.fr/ark:/12148/bpt6k933829z/ isn't identified as being in the public domain. I think https://github.com/rohit-dua/BUB/blob/e7e0010176359579646e4e36e24c5eee4a457f1f/digi-lib/gal.py#L102-L107 is needlessly complicated; now in the HTML I see `<meta name="DC.rights" content="domaine public" /> <meta name="DC.rights" content="public domain" />`, BUB can just parse that.

**Comment by rohit-dua** [comment]
patch: f0f3740
