### ISSUE TITLE
Smarter public domain detection

### ISSUE THREAD

**Issue by nemobis** [rohit-dua/BUB#42]
A bunch of clearly PD books are erroring out as "not public domain", even a book from 1714 for instance: https://books.google.it/books?id=bDoj5_TLj2wC

If the Google API lies or is too reticent, we need to add some logic ourselves. Anything published before 1866 is clearly safe, for instance.

**Comment by nemobis** [comment]
The code doesn't actually check for public domain status in GB, only for viewability. https://www.googleapis.com/books/v1/volumes/BdesBzcRzEkC says "publicDomain": false but most importantly "viewability": "NO_PAGES", so we cannot download anything anyway...

**Comment by LeadSongDog** [comment]
The target is online, it's just that Google isn't making it available. It does however give some helpful hints.  Follow the breadcrumbs:

https://openlibrary.org/works/OL16116024W/L'amante_impazzito --finds catalog data and links to the LCCN
https://lccn.loc.gov/2010665788 --provides the date "[1714?]"
googling "Gasparini 1714 amante" --finds
https://atom.lib.byu.edu/obps/44560/ --which links to
http://www.bibliotecamusica.it/cmbm/scripts/gaspari/scheda.asp?id=16689

There the "SBN" icon links to
http://opac.sbn.it/opacsbn/opac/iccu/scheda.jsp?bid=IT\ICCU\MUS0284285 --at the bottom of which there are two "copia digitalizzata" links, respectively going to 
http://www.braidense.it/risorse/dj.php?bib=IT-MI0185&ser=7&inv=70004500 --and also to
http://www.internetculturale.it/jmms/iccuviewer/iccu.jsp?mode=all&teca=Braidense&id=oai:bid.braidense.it:7:MI0185:MUS0284285
These both seem to be image files for the same paper original, with distinct post-processing leaving the second with higher contrast.

**Comment by nemobis** [comment]
Yes, but we don't download from internetculturale.it.
